Add Jiva-functional experiment into rancher-pipeline
mayadata-io/oep-e2e-rancher pull request #6
Opened 2020-04-30 13:19 UTC by shashank855

Signed-off-by: awesomeshashank855 <ranjanshashank855@gmail.com>

2020-05-02 07:50 UTC, nsathyaseelan approved these changes
Lgtm

2020-05-02 11:31 UTC, harshshekhar15 commented on stages/functional/Jiva-Snapshot-Clone/jiva-snapshot-clone
> +sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/functional/Jiva-Snapshot-Clone/jiva-snapshot-clone node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"'
Pass `commit_id` here as expected by node function.

2020-05-03 02:58 UTC, shashank855 commented on stages/functional/Jiva-Snapshot-Clone/jiva-snapshot-clone
> +sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/functional/Jiva-Snapshot-Clone/jiva-snapshot-clone node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"'
I removed commit ID from node function.

2020-05-03 05:28 UTC, nsathyaseelan requested changes

2020-05-03 05:28 UTC, nsathyaseelan commented on stages/chaos/Jiva-App-kill/jiva-app-kill
> +cd litmus
@shashank855  in which job this litmus directory is cloned

2020-05-03 05:50 UTC, nsathyaseelan requested changes

2020-05-03 05:50 UTC, nsathyaseelan commented on stages/chaos/Jiva-Controller-Network-Delay/ctrl-network-delay
> +case_id=TSXL
@shashank855  can you remove this case_id

2020-05-03 10:05 UTC, nsathyaseelan approved these changes
lgtm

2020-05-03 14:57 UTC, harshshekhar15 approved these changes

2020-05-03 14:58 UTC, merged